"""Ajout de MaNouvelleClasse

Revision ID: aa5095a535b0
Revises: d1b6d28c9e0c
Create Date: 2024-08-22 13:01:39.236801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa5095a535b0'
down_revision = 'd1b6d28c9e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mohsen', sa.Column('Cell_Name', sa.String(length=100), nullable=False))
    op.drop_column('mohsen', 'cell_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mohsen', sa.Column('cell_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('mohsen', 'Cell_Name')
    # ### end Alembic commands ###
