"""Ajout de MaNouvelleClasse

Revision ID: d1b6d28c9e0c
Revises: 
Create Date: 2024-08-22 07:53:35.948644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b6d28c9e0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mohsen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_name', sa.String(length=100), nullable=False),
    sa.Column('mean_rtwp', sa.Float(), nullable=False),
    sa.Column('max_rtwp', sa.Float(), nullable=False),
    sa.Column('min_rtwp', sa.Float(), nullable=False),
    sa.Column('occ_rtwp_gt_98', sa.Float(), nullable=False),
    sa.Column('vs_mean_rtwp_ant0', sa.Float(), nullable=False),
    sa.Column('vs_mean_rtwp_ant1', sa.Float(), nullable=False),
    sa.Column('occ_diff_sect_gt_5', sa.Float(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mohsen_creation_date'), 'mohsen', ['creation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mohsen_creation_date'), table_name='mohsen')
    op.drop_table('mohsen')
    # ### end Alembic commands ###
